[package]
name = "elby"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
http-body-util = "0.1"
hyper = "1.2.0"
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }