[package]
name = "elby"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "1.2.0"
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }